project:
  type: website
  resources:
    - CNAME

execute:
  freeze: auto

website:
  description: "Visual and Physical AI thoughts and tutorials from a former data scientist"
  site-url: https://kierisi.github.io
  title: "Jesse Mostipak"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kierisi
      - icon: bluesky
        href: https://bsky.app/profile/kierisi.bsky.social
format:
  html:
    theme:
      - brite.scss
    css: styles.css



